const HDCONST_CORPORATEARMOUR = 40;
const ENC_CORPORATEARMOUR     = 600;

class HDCorporateArmour : HDArmour {
	default {
		Tag "$TAG_CORPORATEARMOUR";

		Inventory.icon "CARMA0";
		Inventory.pickupmessage "$PICKUP_CORPORATEARMOUR";

		HDPickup.refid "aru";

		HDMagammo.maxperunit HDCONST_CORPORATEARMOUR;
		HDMagammo.magbulk ENC_CORPORATEARMOUR;
	}

	override void Tick() {
		super.Tick();

		if (!(Level.time % (TICRATE * 6))) {
			for (int i = 0; i < mags.size(); i++) if (mags[i] < maxperunit) mags[i] += random(0, 1);
		}
	}

	States {
		Spawn:
			CARM A -1;
			stop;
	}
}

class HDCorporateArmourWorn : HDArmourWorn {

	default {
		Tag "$TAG_CORPORATEARMOUR";

		HDPickup.bulk ENC_CORPORATEARMOUR * 0.65;
		HDPickup.refid "awu";

		HDArmourWorn.armoursprite "CARMA0";
		HDArmourWorn.armourback "CARMB0";

		HDArmourWorn.coverage ARMOUR_TORSO|ARMOUR_ARMS|ARMOUR_LEGS;
		HDArmourWorn.durability HDCONST_CORPORATEARMOUR;
		HDArmourWorn.hindrance 2.35;
		HDArmourWorn.thickness 3;
	}

	override void DoEffect() {
		super.DoEffect();

		if (durability < default.durability && !(Level.time % (TICRATE * 4))) durability += random(0, 1);
	}

	override void Consolidate() {
		super.Consolidate();

		// Fully repairs during downtime
		durability = HDCONST_CORPORATEARMOUR;
	}

	override bool isDamageIgnored(name mod, int flags, int durThresh) {
		return (flags&DMG_NO_ARMOR)
				|| mod == 'staples'
				|| mod == 'maxhpdrain'
				|| mod == 'internal'
				|| mod == 'jointlock'
				|| mod == 'falling'
				// || mod == 'slime'
				|| mod == 'bleedout'
				|| mod == 'drowning'
				|| mod == 'poison'
				// || mod == 'electrical'
				// || durability<random(1, durThresh) //it just goes through a gaping hole in your armour
				|| !owner;
	}

	override int,int,double,int,int,int,int,int HandleDamageType(
		name mod,
		int alv,
		actor inflictor,
		int damage,
		int armourdamage,
		double towound,
		int tobash,
		int toburn,
		int tostun,
		int tobreak,
		int resist
	) {
		switch (mod) {
			case 'slime':
				resist += 10 * (alv + 1);
				if (resist > 0) {
					damage -= resist;
					toburn = min(damage, resist) >> 1;
				}
				break;
			case 'hot':
			case 'cold':
			case 'balefire':
				resist += 10 * (alv + 1);
				if (resist > 0) {
					toburn = min(damage, resist) >> 3;
					if (damage > 21) {
						int olddamage = damage >> 2;
						damage = olddamage >> 3;
						if (!damage && random(0, olddamage)) damage = 1;
						armourdamage = random(0, damage >> 2);
					}
				}
				break;
			case 'electrical':
				resist += 10 * (alv + 1);
				if (resist > 0) {
					toburn = min(damage, resist) >> 3;
					if (damage > 60) {
						int olddamage = damage >> 1;
						damage = olddamage >> 2;
						if (!damage && random(0, olddamage))damage = 1;
						armourdamage = random(0, damage >> 1);
					}
				}
				break;
			case 'piercing':
				resist+=45*(alv+1);
				if(resist>0){
					damage-=resist;
					tobash=min(damage,resist)>>3;
				}
				armourdamage=random(0,damage>>2);
				break;
			case 'slashing':
				resist+=85+25*alv;
				if(resist>0){
					damage-=resist;
					tobash=min(damage,resist)>>2;
				}
				armourdamage=random(0,damage>>2);
				break;

			default:
				return super.HandleDamageType(mod, alv, inflictor, damage, armourdamage, towound, tobash, toburn, tostun, tobreak, resist);
		}

		return damage, armourdamage, towound, tobash, toburn, tostun, tobreak, resist;
	}
}
